# Netlify Configuration for Quadri Adekunle's Portfolio
# Last updated: 2025-09-26

[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"
  CI = "false"

# Redirects - SPA support and legacy URLs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    X-Permitted-Cross-Domain-Policies = "none"
    
    # Content Security Policy
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https:;
      style-src 'self' 'unsafe-inline' https:;
      img-src 'self' data: https:;
      font-src 'self' data: https:;
      connect-src 'self' https:;
      frame-ancestors 'none';
      form-action 'self';
      base-uri 'self';
      object-src 'none';
      upgrade-insecure-requests;
    """
    
    # Feature Policy (legacy)
    Feature-Policy = "geolocation 'none'; microphone 'none'; camera 'none'"
    
    # HSTS (enabled via Netlify UI)
    # Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Caching Headers - JavaScript
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    ETag = "true"

# Caching Headers - CSS
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    ETag = "true"

# Caching Headers - Static Assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    ETag = "true"

# Caching Headers - Media Files
[[headers]]
  for = "/*.(jpg|jpeg|png|gif|ico|svg|webp|mp4|webm|ogg|mp3|wav|flac|aac|woff|woff2|eot|ttf|otf)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    ETag = "true"

# HTML - No Cache
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    ETag = "true"

# Security.txt
[[redirects]]
  from = "/.well-known/security.txt"
  to = "/security.txt"
  status = 200

# Sitemap
[[redirects]]
  from = "/sitemap"
  to = "/sitemap.xml"
  status = 301

# Robots.txt
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

# Error Pages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# 404 - Must be at the end
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = false
  conditions = {Status = "404"}

# Context-specific settings
[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  command = "npm run build"
  environment = { NODE_ENV = "staging" }

[context.branch-deploy]
  command = "npm run build"
  environment = { NODE_ENV = "staging" }

# Analytics (if using Netlify Analytics)
[analytics]
  enabled = true

# Build Plugins
[[plugins]]
  package = "@netlify/plugin-sitemap"
  
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"
  
# Build Environment Variables
[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max_old_space_size=4096"
